const mongoose = require("mongoose")

const MandiSaleSchema = mongoose.Schema({
 itemList:Array,
 date:String,
 billingFarm:String,
 broker:String,
 billNumber:String,
 party:String,
 turnOver:String,
 brokerType:String,
 brokerRate:String,
 id:String,
 produceName:String,
 stockBalance:String,
 supplyPoint:String,
 discountRate:String,
 discount:String,
 totalSum:String,
 cgstRate:String,
 sgstRate:String,
 igstRate:String,
 cgst:String,
 sgst:String,
 igst:String,
 freightRate:String,
 totalFreight:String,
 advanceFreight:String,
 tcs:String,
 roundOff:String,
 lastAmount:String,
 partyAddress:String,
 partyPinCode:String,
 partyCity:String,
 partyState:String,
 partyGstin:String,
 transporterName:String,
 truckNo:String,
 driverName:String,
 driverLicenceNo:String,
 driverMobileNo:String,
 biltiNo:String,
 contractNo:String,
 anugyaNo:String,
 ewayBillNo:String,
   
})

module.exports = mongoose.model("MandiSale", MandiSaleSchema);